FORMAT: 1A
HOST: http://www.wantoto.com

# DEV台大醫院行動醫療資訊系統 Web Service 0.35
採用 RESTful 架構規劃。所有字串編碼皆為UTF-8。

# 9/22-登入與取得 SessionKey [/sessionKey{?empNo,password}]
## 取得 session key[POST]
+ Parameters
    + empNo (string) ... 使用者帳號
    + password (string) ... 使用者密碼

+ Response 200 (application/json)

        {
            "content" : {
                "empName" : "葉小菜",    //員工姓名[string]
                "sessionKey" : "51ADFDA9C02D4E1E9930D88A26963612" //Session key [string]
            }
        }
    
+ Response 401 (application/json)

        {
            "message" : "帳號密碼錯誤", //錯誤訊息[string]
            "error" : 101 //錯誤代碼 [number]
        }

# Group Web Service 通則
## 通則 [/{?sessionKey,offset,limit}]
### 驗證 Session Key 與資料分頁參數[GET]
所有 Web Service 都須帶入 Session Key 檢查是否過期與是否具有存取權限。

過期則回傳 401；無存取權限則回傳 403。

所有資料回傳時間，皆以時間序號表示，以秒為單位。
(使用 1 January 1970, GMT為基準時間 http://zh.wikipedia.org/wiki/Help:%E6%99%82%E9%96%93%E5%BA%8F%E8%99%9F）
+ Parameters
    + sessionKey (string) ... 使用者登入 Session Key
    + offset = `0` (number, optional) ... 資料偏移數，需與 limit 一起傳入，當content為陣列或collection時使用
    + limit (number, optional) ... 最大回傳筆數，需與 offset 一起傳入，當content為陣列或collection時使用
    
+ Response 200 (application/json)
        
        {
            "content" : [], //回傳內容(可以是單一物件，也可以是陣列)
            "limit" : 50, //最大回傳筆數，當client傳入時需回傳[number] 
            "offset" : 0, //回傳資料偏移數，當client傳入時需回傳[number]
            "total" : 100 //此次Query總筆數，當content為陣列或collection時需回傳[number] 
        }

+ Response 401 (application/json)

        {
            "message" : "Session Key 過期", //錯誤訊息[string]
            "error" :  102 //錯誤代碼 [number]
        }
        
+ Response 403 (application/json)

        {
            "message" : "無存取權限", //錯誤訊息[string]
            "error" :  103 //錯誤代碼 [number]
        }

# Group 病患清單 Patient List
病患清單相關 Web Service
## 9/22-病患清單 [/patients{?patientID,personID,wardCode,empNo,empNoConsult,empNoStarred,ORCode,ERCode,OPDCode,examRoomCode}]
### 查詢病患清單 [GET]
可傳入病歷號、身分證號、病房、醫師員編、開刀房號、急診科別、門診科別、檢查科室等參數，回傳符合參數條件之病患
+ Parameters
    + patientID (string, optional) ... 病歷號
    + personID (string, optional) ... 身分證號
    + wardCode (string, optional, `5W3`) ... 病房號
    + empNo (string, optional) ... 醫師員編 (依照醫師員編顯示個人病患)
    + empNoConsult (string, optional) ... 醫師員編 (依照醫師員編顯示照會病患)
    + empNoStarred (string, optional) ... 醫師員編 (依照醫師員編顯示追蹤病患)
    + ORCode (string, optional) ... 開刀房號
    + ERCode (string, optional) ... 急診科別
    + OPDCode (string, optional) ... 門診科別
    + examRoomCode (string, optional) ... 檢查科室
    
+ Response 200 (application/json)

        {
            "content" : [   //病患資訊陣列
                {   //病患資訊
                    "patName" : "王小明",  //病患姓名[string]
                    "patSexCode" : "M",   //性別[string]（男性："M";女性："F"）
                    "patBirthday" : 1406938026,    //出生日期[number(date)]
                    "patientID" : "12345678",   //病歷號[string]
                    "persionID" : "A123456789",  //身分證號[number]
                    "bedInfo" : "5W3 01-01",    //病房病床號(住院與急診)[string]
                    "inDate" : 1406938026, //入院日期(住院與急診)，非住院或在急診則回傳 null [number(date)]
                    "_emp_VS" : {   //主治醫師(如遇回傳資料為醫師者，變數皆為_emp_開頭)[string]
                        "empNo" : "111281", //醫師員編[string]
                        "name" : "葉小菜" 
                    },
                    "status" : "住院中" //狀態[string]
                    "specialTag" : [   //特殊標記[string array] (ex:DNR,...)
                        {
                            "tagCode" : "DNR",
                            "displayName" : "DNR"
                        },
                        ...
                    ],
                    "latestPacsReportDateTime" : 1406938026, //最新影像時間[number(date)]
                    "latestLISReportDateTime" : 1406938026, //最新報告時間[number(date)]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }
        
## 病房號 [/wards]
### 查詢所有病房 [GET]
+ Response 200 (application/json)

        {
            "content" : [   //病房資訊陣列
                {   //病房資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "wardCode" : "01A1",   //病房代碼[string]
                    "displayName" : "01A1"    //顯示名稱[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }
        
## 開刀房號 [/ORs]
### 查詢開刀房 [GET]
+ Response 200 (application/json)

         {
            "content"[   //手術房資訊陣列
                {   //手術房資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "ORCode" : "1",   //開刀房代碼[string]
                    "displayName" : "1"    //顯示名稱[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }
        
## 急診科別 [/ERs]
### 查詢急診科別 [GET]
+ Response 200 (application/json)

         {
            "content"[   //急診科別資訊陣列
                {   //急診科別資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "ERCode" : "ALL",   //急診科別代碼[string]
                    "displayName" : "不分科"    //顯示名稱[string]
                },
                {   //急診科別資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "ERCode" : "MED",   //急診科別代碼[string]
                    "displayName" : "非外傷"    //顯示名稱[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }
    
## 門診科別 [/OPDs]
### 查詢今日門診科別 [GET]
+ Response 200 (application/json)

        {
            "content" : [   //門診科別資訊陣列
                {   //門診科別資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "OPDCode" : "MED",   //門診科別代碼[string]
                    "displayName" : "內科部",    //顯示名稱[string]
                    "childPath" : "/OPDs/MED"   //下一層內容連結，無下層則不回傳[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }

## 門診科別層級 [/OPDs/{OPDCode}]
### 查詢今日門診科別 [GET]
+ Parameters 
   + OPDCode (string, `MED`) ... 門診代碼

+ Request MED (text/plain)

        "OPDCode" : "MED"

+ Response 200 (application/json)
        
        {
            "content" : [   //門診科別資訊陣列
                {
                    "hospCode" : "T0",  //醫院代碼[string]
                    "OPDCode" : "MED_A",   //門診科別代碼[string]
                    "displayName" : "內科部 上午",    //顯示名稱[string]
                    "childPath" : "/OPDs/MED_A"   //下一層內容連結，無下層則不回傳[string]
                },
                {
                    "hospCode" : "T0",  //醫院代碼[string]
                    "OPDCode" : "MED_P",   //門診科別代碼[string]
                    "displayName" : "內科部 下午",    //顯示名稱[string]
                    "childPath" : "/OPDs/MED_P"   //下一層內容連結，無下層則不回傳[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }

+ Request MED_A (text/plain)

        "OPDCode" : "MED_A"

+ Response 200 (application/json)
        
        {
            "content" : [   //門診科別資訊陣列
                {   //門診科別資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "OPDCode" : "MED_A_01",   //門診科別代碼[string]
                    "displayName" : "01診 王OO 腎臟科",    //顯示名稱[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        }

## 檢查科室 [/examRooms]
### 查詢檢查科室 [GET]
+ Response 200 (application/json)

        {
            "content" : [   //檢查科別資訊陣列
                {   //檢查科別資訊
                    "hospCode" : "T0",  //醫院代碼[string]
                    "examRoomCode" : "000CPFT0",   //檢查科室代碼[string]
                    "displayName" : "[檢查照會] 肺功能室",    //顯示名稱[string]
                    "childPath" : "/examRooms/000CPFT0"   //下一層內容連結，無下層則不回傳[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50 //此次Query總筆數[number] 
        ]

## 檢查科室層級 [/examRooms/{examRoomCode}]
### 查詢檢查科室 [GET]
+ Parameters 
   + examRoomCode (string, `000CPFT0`) ... 檢查科室代碼
   
+ Request MED (text/plain)

        "examRoomCode" : "000CPFT0"
        
+ Response 200 (application/json)

        {
            "content" : [   //檢查科別資訊陣列
                {
                    "hospCode" : "T0",  //醫院代碼[string]
                    "examRoomCode" : "000CPFT0_A",   //檢查科室代碼[string]
                    "displayName" : "[檢查照會] 肺功能室 上午",    //顯示名稱[string]
                },
                {
                    "hospCode" : "T0",  //醫院代碼[string]
                    "examRoomCode" : "000CPFT0_P",   //檢查科室代碼[string]
                    "displayName" : "[檢查照會] 肺功能室 上午",    //顯示名稱[string]
                },
                {
                    "hospCode" : "T0",  //醫院代碼[string]
                    "examRoomCode" : "000CPFT0_N",   //檢查科室代碼[string]
                    "displayName" : "[檢查照會] 肺功能室 晚上",    //顯示名稱[string]
                }
            ],
            "limit" : 3, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 3 //此次Query總筆數[number] 
        ]

# Group 病歷資料 Medical Record
## @病患醫療基本資料 [/patients/{patientID}]
### 取得病患醫療基本資料 [GET]
+ Parameters 
    + patientID (string) ... 病歷號

+ Response 200 (application/json)
        
        {
            "content" : {
            } 
        }

## 病歷資料 Web Service 通則 [/patients/{patientID}/{dataPath}{?startDate,endDate}]
### 取得病歷資料 [GET]
+ Parameters
    + patientID (string) ... 病歷號
    + dataPath (string) ... 各項病歷資料路徑
    + startDate = `入院日` (string, optional, `1406938026`) ... Query 起始日期，以時間序號表示 (包含此日期)
    + endDate = `今日` (string, optional, `1406938026`) ... Query 結束日期，以時間序號表示 (包含此日期)
+ Response 200 (application/json)
        
        {
            "content" : [], //回傳內容(可以是單一物件，也可以是陣列)
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026, Query 結束日期，以時間序號表示 (包含此日期)
            "limit" : 50, //最大回傳筆數，當client傳入與content為陣列或collection時需回傳[number] 
            "offset" : 0, //回傳資料偏移數，當client傳入與content為陣列或collection時需回傳[number]
            "total" : 100 //此次Query總筆數，當content為陣列或collection時需回傳[number] 
        }

## 9/22-檢驗報告-清單報告 [/patients/{patientID}/labReport/report]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "data" [
                    {   //檢驗報告
                        "specimen" : "BLOOD", //檢體[string]
                        "lab" : "血液檢驗組血液室HE",    //檢驗單位[string]
                        "requestNo" : "4025928",    //檢驗單號[string]
                        "inspectionDate" : 1406938026,   //採檢時間[number(date)]
                        "recordDate" : 1406938026,    //登入時間[number(date)]
                        "reportDate" : 1406938026,   //最後報告時間[number(date)]                        
                        "filterCode" : [    //篩選代碼
                            "HE"
                        ],
                        "report" : {    //有額外報告時回傳
                            "reportType" : "HTML",  //報告型態，HTML或PDF
                            "reportPath" : "/labReport/{labReportID}"   //報告路徑
                        },
                        "table" : {
                            "field" : [    //欄位資訊
                                {
                                    "fieldCode" : "item",  //欄位代碼[string]
                                    "displayName" : "檢驗項目" //欄位顯示名稱[string]
                                },
                                {
                                    "fieldCode" : "labValue",  
                                    "displayName" : "檢驗值"
                                },
                                {
                                    "fieldCode" : "unit",  
                                    "displayName" : "單位"
                                },
                                {
                                    "fieldCode" : "reference",  
                                    "displayName" : "參考值"
                                },
                                {
                                    "fieldCode" : "critical",  
                                    "displayName" : "危急值"
                                },
                                {
                                    "fieldCode" : "note",  
                                    "displayName" : "說明"
                                },
                                {
                                    "fieldCode" : "specialOrder",  
                                    "displayName" : "特別醫囑"
                                }
                            ],
                            "data" : [
                                {
                                    "content" : {   //依據欄位填入資料，無資料則不回傳
                                        "item" : "RBC",
                                        "labValue" : {   //若為檢驗數值則回傳object
                                            "value" :"2.66",    //檢驗值[string]
                                            "status" : "normal"    //檢驗值狀態。ex:"normal"(正常)、"abnormal"(異常)、"low"(過低)、"high"(過高)、"unknow"(無法判斷)[string]
                                        },
                                        "unit" : "M/ul",
                                        "reference" : "4 ~ 5.52",
                                        "critical" : "< 2.0 & > 7.0", 
                                        "note" : "", 
                                        "specialOrder" : ""                         
                                    }
                                },
                                ...
                            ],
                        }
                    },
                    ...
                ],
                "filter" : [
                    {
                        "filterCode" : "HE",
                        "displayName" : "血液檢驗組血液室HE"
                    },
                    {
                        "filterCode" : "BC",
                        "displayName" : "生化檢驗組BC"
                    },
                    ...
                ],
                "limit" : 50, //最大回傳筆數，當client傳入與content為陣列或collection時需回傳[number] 
                "offset" : 0, //回傳資料偏移數，當client傳入與content為陣列或collection時需回傳傳[number]
                "total" : 100 //此次Query總筆數，當content為陣列或collection時需回傳[number] 
            }, 
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026, Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/22-檢驗報告-累積報告 [/patients/{patientID}/labReport/accmulatedReport]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "data" [
                    {   
                        "item" : "CBC+PLT BLOOD", //檢驗項目[string]
                        "lab" : "血液檢驗組血液室HE",    //檢驗單位[string]
                        "filterCode" : [    //篩選代碼
                            "HE"
                        ],
                        "table" : {
                            "field" : [    //欄位資訊
                                {
                                    "fieldCode" : "date",  //欄位代碼[string]
                                    "displayName" : "檢驗時間", //欄位顯示名稱[string]
                                    "dateFormat" : "yyyy-MM-dd hh:mm"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                                },
                                {
                                    "fieldCode" : "WBC",  
                                    "displayName" : "WBC(k/uL)"
                                    "labInfo" : {   //檢驗項目相關資訊[string]
                                        "reference" : "3.54 ~ 9.06" //參考值[string]
                                    }
                                    
                                },
                                ...
                            ],
                            "data" : [
                                {
                                    "reportDate" : 1406938026,  //報告時間[number(date)]
                                    "content" : {   //依據欄位填入資料，無資料則不回傳
                                        "date" : 1406938026,
                                        "WBC" : {   //若為檢驗數值則回傳object
                                            "value" :"4.05",    //檢驗值[string]
                                            "status" : "normal",    //檢驗值狀態。ex:"normal"(正常)、"abnormal"(異常)、"low"(過低)、"high"(過高)、"unknow"(無法判斷)[string]
                                            "note" : "123" //檢醫部註記，無資料則不回傳[sitrng]
                                        },
                                    },
                                },
                                ...
                            ],
                        }
                    },
                    ...
                ],
                "filter" : [
                    {
                        "filterCode" : "HE",
                        "displayName" : "血液檢驗組血液室HE"
                    },
                    {
                        "filterCode" : "BC",
                        "displayName" : "生化檢驗組BC"
                    },
                    ...
                ],
            }, 
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026, Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/22-檢驗報告-綠單報告 [/patients/{patientID}/labReport/greenReport]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "data" [
                    {   
                        "item" : "Complete Blood Cell Count BLOOD", //綠單項目[string]
                        "filterCode" : [    //篩選代碼
                            "CBC"
                        ],
                        "table" : {
                            "field" : [    //欄位資訊
                                {
                                    "fieldCode" : "date",  //欄位代碼[string]
                                    "displayName" : "檢驗時間", //欄位顯示名稱[string]
                                    "dateFormat" : "yyyy-MM-dd hh:mm"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                                },
                                {
                                    "fieldCode" : "WBC",  
                                    "displayName" : "WBC(k/uL)"
                                    "labInfo" : {   //檢驗項目相關資訊[string]
                                        "reference" : "3.54 ~ 9.06" //參考值[string]
                                    }
                                    
                                },
                                ...
                            ],
                            "data" : [
                                {
                                    "reportDate" : 1406938026,  //報告時間[number(date)]
                                    "content" : {   //依據欄位填入資料，無資料則不回傳
                                        "date" : 1406938026,
                                        "WBC" : {   //若為檢驗數值則回傳object
                                            "value" :"4.05",    //檢驗值[string]
                                            "status" : "normal",    //檢驗值狀態。ex:"normal"(正常)、"abnormal"(異常)、"low"(過低)、"high"(過高)、"unknow"(無法判斷)[string]
                                            "note" : "123" //檢醫部註記，無資料則不回傳[sitrng]
                                        },
                                    },
                                },
                                ...
                            ],
                        }
                    },
                    ...
                ],
                "filter" : [
                    {
                        "filterCode" : "CBC",
                        "displayName" : "CBC"
                    },
                    {
                        "filterCode" : "biochemistry",
                        "displayName" : "Biochemistry"
                    },
                    ...
                ],
            }, 
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026, Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/15-報告系統 [/patients/{patientID}/otherReport]
檢驗報告之外的其他報告
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "field" : [    //欄位資訊
                    {
                        "fieldCode" : "items",  
                        "displayName" : "檢查項目"
                    },
                    {
                        "fieldCode" : "date",  //欄位代碼[string]
                        "displayName" : "報告時間", //欄位顯示名稱[string]
                        "dateFormat" : "yyyy-MM-dd hh:mm"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                    },
                    {
                        "fieldCode" : "type",  
                        "displayName" : "報告種類"
                    }
                ],
                "data" : [
                    {
                        "content" : {   //依據欄位填入資料，無資料則不回傳
                            "date" : 1406938026,
                            "item" : "Chest PA View (Standing)",
                            "type" : "影核醫"
                        },
                        "filterCode" : [    //篩選類別
                            "image"
                        ],
                        "report" : {    //如有報告則回傳
                            "reportType" : "HTML",  //報告型態，HTML或PDF
                            "reportPath" : "/imageReport/{imageReportID}"   //報告路徑
                        }
                    },
                    ...
                ],
                "filter" : [
                    {
                        "filterCode" : "image",
                        "displayName" : "影核醫"
                    },
                    {
                        "filterCode" : "ECG",
                        "displayName" : "心電圖"
                    },
                    ...
                ],
                "limit" : 50, //最大回傳筆數傳[number] 
                "offset" : 0, //回傳資料偏移數[number]
                "total" : 100 //此次Query總筆數[number]
            },
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026 Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/22-生命徵象 [/patients/{patientID}/TPR]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "TPR" : [   //TPR 圖表資料
                    {   //每次TPR紀錄
                        "date" : 1406938026,    //紀錄時間[nubmer(date)]
                        "breathing" : 20,   //呼吸[number,optional]
                        "temperature" : 37.5,   //體溫[number,optional]
                        "heartRate" : 59,    //心跳[number,optional]
                        "bloodPressure" : { //血壓
                            "systolic" : 116,    //收縮壓[number,optional]
                            "diastolic" : 69    //舒張壓[number,optional]
                        }    
                    },
                    ...
                ],
                "IO" : [    //IO資料
                    {   //欄位資料
                        "fieldName" : "血壓", //欄位名稱[string]
                        "data" : [
                            {
                                "date" : 1406938026,    //資料時間[number(date)]
                                "data" : "125/75"   //資料內容[string]
                            },
                            ...
                        ]
                    },
                    {   //欄位資料
                        "fieldName" : "身高", //欄位名稱[string]
                        "unit" : "cm",  //單位，有單位時回傳[string,optional]
                        "data" : [
                            {
                                "date" : 1406938026,    //資料時間[number(date)]
                                "data" : "173"   //資料內容[string]
                            },
                            {
                                "date" : 1406948026,    //資料時間[number(date)]
                                "data" : "173.5"   //資料內容[string]
                            },
                            ...
                        ]
                    },
                ],
                "medication" : [
                    {
                        "drugName" : "Magnesium Oxide", //學名[string]
                        "itemName" : "MgO", //品名[string]
                        "itemUnit" : "250 mg/tab", //劑量單位[string]
                        "medicationID" : "MET4FB18", //藥品八碼[string]
                        "dose" : "2 tab", //劑量[string]
                        "approach" : "PO", //途徑[string]
                        "frequency" : "BID", //頻次[string]
                        "orderDate" : 1406938026, //開立日期[number(date)]
                        "startDate" : 1406938026, //用藥開始日期[number(date)]
                        "endDate" : 1406938026, //用藥結束日期[number(date)]
                        "_emp_order" : { //開立醫師
                            "empNo" : "23454353",
                            "name" : "葉小菜"
                        },
                        "note" : "自費 特殊醫囑: For scrotal ulcers", //備註[string]
                        "category" : "other", //處方類別。ex:"anti"(抗生素)、"anodyne"(止痛藥)、"other"(其他)[string]
                        "drugInfoPath" : "/medication/{medicationID}",  //藥物資訊連結[string]
                        "drugRecord" : [    //Query期間所有給藥記錄
                            {
                                "date" : 1406938026, //日期[number(date)]
                                "status" : "taken", //用藥狀態。ex:"taken"(已給藥)、"pending"(未處理)、"failure"(未給藥)[string]
                                "note" : "", //護理給藥備註[string]
                                "executor" : "張小珍 護理師" //執行人員[string]
                            },
                            ...
                        ]
                    },
                    ...
                ]
            },
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026 Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/22-非處方醫囑 [/patients/{patientID}/order]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "field" : [    //欄位資訊
                    {
                        "fieldCode" : "order",  
                        "displayName" : "醫令內容"
                    },
                    {
                        "fieldCode" : "startDate",  //欄位代碼[string]
                        "displayName" : "開始時間", //欄位顯示名稱[string]
                        "dateFormat" : "yyyy-MM-dd"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                    },
                    {
                        "fieldCode" : "endDate",  //欄位代碼[string]
                        "displayName" : "結束時間", //欄位顯示名稱[string]
                        "dateFormat" : "yyyy-MM-dd"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                    },
                    {
                        "fieldCode" : "_emp_doctor",  
                        "displayName" : "確認醫師"
                    },
                    {
                        "fieldCode" : "status",  
                        "displayName" : "狀態"
                    },
                    {
                        "fieldCode" : "orderDate",  
                        "displayName" : "開立時間",
                        "dateFormat" : "yyyy-MM-dd mm:ss"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                    }
                ],
                "data" : [
                    {
                        "content" : {   //依據欄位填入資料，無資料則不回傳
                            "order" : "Chest PA View (Standing)",
                            "startDate" : 1406938026,
                            "endDate" : 1406938026,
                            "_emp_doctor" : { 
                                "empNo" : "23454353",
                                "name" : "葉小菜"
                            },
                            "status" : "已完成",
                            "orderDate" : 1406938026
                        },
                        "filterCode" : [    //篩選類別
                            "image"
                        ],
                        "report" : {    //如有報告則回傳
                            "reportType" : "HTML",  //報告型態，HTML或PDF
                            "reportPath" : "/ImageReport/{ImageReportID}"   //報告路徑
                        }
                    },
                    ...
                ],
                "filter" : [
                    {
                        "filterCode" : "order",
                        "displayName" : "醫囑"
                    },
                    {
                        "filterCode" : "medication",
                        "displayName" : "處方"
                    },
                    {
                        "filterCode" : "lab",
                        "displayName" : "檢驗"
                    },
                    {
                        "filterCode" : "image",
                        "displayName" : "影醫"
                    },
                    ...
                ],
                "limit" : 50, //最大回傳筆數傳[number] 
                "offset" : 0, //回傳資料偏移數[number]
                "total" : 100 //此次Query總筆數[number]
            },
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026 Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/22-處方醫囑 [/patients/{patientID}/medication]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : [
                {
                    "drugName" : "Magnesium Oxide", //學名[string]
                    "itemName" : "MgO", //品名[string]
                    "itemUnit" : "250 mg/tab", //劑量單位[string]
                    "medicationID" : "MET4FB18", //藥品八碼[string]
                    "dose" : "2 tab", //劑量[string]
                    "approach" : "PO", //途徑[string]
                    "frequency" : "BID", //頻次[string]
                    "orderDate" : 1406938026, //開立日期[number(date)]
                    "startDate" : 1406938026, //用藥開始日期[number(date)]
                    "endDate" : 1406938026, //用藥結束日期[number(date)]
                    "_emp_order" : { //開立醫師
                        "empNo" : "23454353",
                        "name" : "葉小菜"
                    },
                    "note" : "自費 特殊醫囑: For scrotal ulcers", //備註[string]
                    "category" : "prolonged", //處方類別。ex:"prolonged"(長期)、"stat"(臨時)、"cancel"(取消)、"own"(自備藥)[string]
                    "drugInfoPath" : "/medication/{medicationID}",  //藥物資訊連結[string]
                    "drugRecord" : [    //Query期間所有給藥記錄
                        {
                            "date" : 1406938026, //日期[number(date)]
                            "status" : "taken", //用藥狀態。ex:"taken"(已給藥)、"pending"(未處理)、"failure"(未給藥)[string]
                            "note" : "", //護理給藥備註[string]
                            "executor" : "張小珍 護理師" //執行人員[string]
                        },
                        ...
                    ]
                },
                ...
            ],
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026, Query 結束日期，以時間序號表示 (包含此日期)
            "limit" : 50, //最大回傳筆數，當client傳入時需回傳[number] 
            "offset" : 0, //回傳資料偏移數，當client傳入時需回傳[number]
            "total" : 100 //此次Query總筆數，當content為陣列或collection時需回傳[number] 
        }

## 9/15-藥物資訊 [/medication/{medicationID}]
### 取得藥物資訊 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "drugName" : "Mecobalamin", //學名[string]
                "itemName" : "Methycobal Capsule 500 mcg / cap", //品名[string]
                "chineseName" : "彌可保膠囊", //中文名[string]
                "aliases" : "", //別名[string]
                "formulations" : "硬膠囊", //劑型[string]
                "medicationID" : "MET4FB18" //藥品八碼[string]
                "pharmaClassification" : "VIII. Hematological Agents\r1. Agents Used to Treat Deficiency Anemia" //藥理分類，如需換行換行符號為"\r"[string]
                "usualDose" : "Peripheral neuropathies:\rPO, 500 mcg tid.", //常用劑量[string]
                "indications" : "末梢性神經障礙", //適應症[string]
                "maxDose" : "BID", // 最大劑量[string]
                "PregnantClassification" : "", //懷孕分級[string]
                "Contraindications" : "", //禁忌[string]
                "role" : "補充維他命Ｂ１２", //作用[string]
                "drugSafetyAlert" : "", //藥物安全警訊[string]
                "sideEffects" : "可能引起胃部不適、過敏反應等。", //副作用[string]
                "precautions" : "", //注意事項[string]
                "storage" : "≦ 30 ℃ & protect from light.", //儲存方法[string]
                "DrugDealers" : "衛采製藥股份有限公司", //藥商[string]
                "appearanceImages" : [ //藥品外觀圖片連結
                    "https://dept.ntuh.gov.tw/phar/DrugImage/New/s/MET4FB18-A.JPG",
                    "https://dept.ntuh.gov.tw/phar/DrugImage/New/s/MET4FB18-B.JPG"
                ]
            }
        }


## 9/22-手術紀錄 [/patients/{patientID}/OPNote]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "field" : [    //欄位資訊
                    {
                        "fieldCode" : "OPType",  
                        "displayName" : "術式"
                    },
                    {
                        "fieldCode" : "dept",  
                        "displayName" : "科部"
                    },
                    {
                        "fieldCode" : "date",  //欄位代碼[string]
                        "displayName" : "手術開始時間", //欄位顯示名稱[string]
                        "dateFormat" : "yyyy-MM-dd hh:mm"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                    },
                    {
                        "fieldCode" : "_emp_doctor",  
                        "displayName" : "醫師"
                    },
                    {
                        "fieldCode" : "status",  
                        "displayName" : "狀態"
                    }
                ],
                "data" : [
                    {
                        "content" : {   //依據欄位填入資料，無資料則不回傳
                            "OPType" : "1. Subxiphoid drainage with sternal... ",
                            "dept" : "外科部",
                            "date" : 1406938026,
                            "_emp_doctor" : {
                                "empNo" : "123342"
                                "name" : "葉小菜"
                            },
                            "status" : "V"
                        },
                        "report" : {    //如有報告則回傳
                            "reportType" : "HTML",  //報告型態，HTML或PDF
                            "reportPath" : "/OPNote/{OPNoteID}"   //報告路徑
                        }
                    },
                    ...
                ],
                "limit" : 50, //最大回傳筆數傳[number] 
                "offset" : 0, //回傳資料偏移數[number]
                "total" : 100 //此次Query總筆數[number]
            }
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026, Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/15-病程紀錄 [/patients/{patientID}/progressNote]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "field" : [    //欄位資訊
                    {
                        "fieldCode" : "type",  
                        "displayName" : "類別"
                    },
                    {
                        "fieldCode" : "date",  //欄位代碼[string]
                        "displayName" : "報告時間", //欄位顯示名稱[string]
                        "dateFormat" : "yyyy-MM-dd hh:mm"   //若此欄位資訊為時間，則回傳顯示格式，非時間則不回傳[string]
                    },
                    {
                        "fieldCode" : "status",  
                        "displayName" : "狀態"
                    }
                ],
                "data" : [
                    {
                        "content" : {   //依據欄位填入資料，無資料則不回傳
                            "date" : 1406938026,
                            "status" : "V",
                            "type" : "Admission Note"
                        },
                        "filterCode" : [    //篩選類別
                            "ADM"
                        ],
                        "report" : {    //如有報告則回傳
                            "reportType" : "HTML",  //報告型態，HTML或PDF
                            "reportPath" : "/progressNote/{progressNoteID}"   //報告路徑
                        }
                    },
                    ...
                ],
                "filter" : [
                    {
                        "filterCode" : "ADM",
                        "displayName" : "Admission Note"
                    },
                    {
                        "filterCode" : "PRO",
                        "displayName" : "Progress Note"
                    },
                    ...
                ],
                "limit" : 50, //最大回傳筆數傳[number] 
                "offset" : 0, //回傳資料偏移數[number]
                "total" : 100 //此次Query總筆數[number]
            }
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026 Query 結束日期，以時間序號表示 (包含此日期)
        }

## 9/15-電子病歷 [/patients/{patientID}/EMR]
### 取得病歷資料 [GET]

+ Response 200 (application/json)
        
        {
            "content" : {
                "field" : [    //欄位資訊
                    {
                        "fieldCode" : "item",  
                        "displayName" : "項目"
                    }
                ],
                "data" : [
                    {
                        "content" : {   //依據欄位填入資料，無資料則不回傳
                            "item" : "置頂",
                        },
                        "children" : [  //有次階層時回傳
                            {
                                "content" : {   //依據欄位填入資料，無資料則不回傳
                                    "item" : "病歷首頁及摘要",
                                },
                                "report" : {    //如有報告則回傳
                                    "reportType" : "HTML",  //報告型態，HTML或PDF
                                    "reportPath" : "/EMRReport/{EMRReportID}"   //報告路徑
                                },
                                "children" : [
                                    {
                                        "content" : {   //依據欄位填入資料，無資料則不回傳
                                            "item" : "PDF病歷首頁及摘要",
                                        },
                                        "report" : {    //如有報告則回傳
                                            "reportType" : "PDF",  //報告型態，HTML或PDF
                                            "reportPath" : "/EMRReport/{EMRReportID}"   //報告路徑
                                        }
                                    },
                                    ...
                                ]
                            },
                            ...
                        ]
                    },
                    {
                        "content" : {   //依據欄位填入資料，無資料則不回傳
                            "item" : "住院",
                        },
                        "children" : [
                            {
                                "content" : {   //依據欄位填入資料，無資料則不回傳
                                    "item" : "2014/06/25 外科部",
                                },
                                "children" : [
                                    {
                                        "content" : {   //依據欄位填入資料，無資料則不回傳
                                            "item" : "出院病摘",
                                        },
                                        "report" : {    //如有報告則回傳
                                            "reportType" : "HTML",  //報告型態，HTML或PDF
                                            "reportPath" : "/EMRReport/{EMRReportID}"   //報告路徑
                                        }
                                        "children" : [
                                            {
                                                "content" : {   //依據欄位填入資料，無資料則不回傳
                                                    "item" : "2014/06/25 葉小菜主治",
                                                },
                                                "report" : {    //如有報告則回傳
                                                    "reportType" : "PDF",  //報告型態，HTML或PDF
                                                    "reportPath" : "/EMRReport/{EMRReportID}"   //報告路徑
                                                }
                                            },
                                            ...
                                        ]
                                    },
                                    ...
                                ]
                            },
                            ...
                        ]
                    },
                    ...
                ],
                "limit" : 50, //最大回傳筆數傳[number] 
                "offset" : 0, //回傳資料偏移數[number]
                "total" : 100 //此次Query總筆數[number]
            },
            "startDate" : 1406938026, Query 起始日期，以時間序號表示 (包含此日期)
            "endDate" : 1406938026 Query 結束日期，以時間序號表示 (包含此日期)
        }

# Group 其他 Other Web Service
## 9/24-通訊錄 [/contacts{?offset,limit}]
### 取得資料 [GET]

+ Parameters
    + offset = `0` (number, optional) ... 資料偏移數，需與 limit 一起傳入
    + limit (number, optional) ... 最大回傳筆數，需與 offset 一起傳入
    
+ Response 200 (application/json)
        
        {
            "content" : [
                {
                    "empNo" : "123456", //員工編號[string]
                    "empName" : "葉小菜",    //員工姓名[string]
                    "DEPT" : "內科部",  //單位[string]
                    "division" : "腸胃科",  //二級單位[string]
                    "title" : "主治醫師",   //職稱[string]
                    "TEL" : "71707",    //院內電話[string]
                    "mobile" : "0972111222",    //公務手機[string]
                    "mobileBriefCode" : "11222", //手機簡碼[string]
                    "EngFirstName" : "Hao-Tsai",    //英文首名[string]
                    "EngLastName" : "Yeh",  //英文姓[string]
                    "EngMiddleName" : "", //英文中名[string]
                    "email" : "xxx@ntuh.gov.tw", //email[string]
                    "remark" : ""   //備註[string]
                },
                ...
            ], 
            "limit" : 50, //最大回傳筆數[number] 
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 100 //此次Query總筆數[number] 
        }




